name : Test fact

on: 
  push:
    branches: [ master ]

jobs:

  build:
    name: Test Build
    runs-on: ubuntu-latest 
    steps:
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      
      - name: Run a one-line script
        uses: actions/checkout@v2
     
      - name: install
        run: apt-get install python3-psutil
        
      - name: Build
        run: python3 fact_test.py
